using System.Collections.Generic;

namespace StellaQL.Acons.Main_Char3
{
    /// <summary>
    /// This file was automatically generated.
    /// It was created by [Generate C# (Fullpath of all states)] button.
    /// </summary>
    public abstract class Main_Char3_AbstractAControl : AbstractAControl
    {
        public const string
            BASELAYER_ = "Base Layer.",
            BASELAYER_CATKHK = "Base Layer.CAtkHK",
            BASELAYER_CATKHP = "Base Layer.CAtkHP",
            BASELAYER_CATKLK = "Base Layer.CAtkLK",
            BASELAYER_CATKLP = "Base Layer.CAtkLP",
            BASELAYER_CATKMK = "Base Layer.CAtkMK",
            BASELAYER_CATKMP = "Base Layer.CAtkMP",
            BASELAYER_CBLOCKH = "Base Layer.CBlockH",
            BASELAYER_CBLOCKL = "Base Layer.CBlockL",
            BASELAYER_CBLOCKM = "Base Layer.CBlockM",
            BASELAYER_CDAMAGEH = "Base Layer.CDamageH",
            BASELAYER_CDAMAGEL = "Base Layer.CDamageL",
            BASELAYER_CDAMAGEM = "Base Layer.CDamageM",
            BASELAYER_CMOVE = "Base Layer.CMove",
            BASELAYER_CWAIT = "Base Layer.CWait",
            BASELAYER_DATKHK = "Base Layer.DAtkHK",
            BASELAYER_DATKHP = "Base Layer.DAtkHP",
            BASELAYER_DATKLK = "Base Layer.DAtkLK",
            BASELAYER_DATKLP = "Base Layer.DAtkLP",
            BASELAYER_DATKMK = "Base Layer.DAtkMK",
            BASELAYER_DATKMP = "Base Layer.DAtkMP",
            BASELAYER_DBLOCKH = "Base Layer.DBlockH",
            BASELAYER_DBLOCKL = "Base Layer.DBlockL",
            BASELAYER_DBLOCKM = "Base Layer.DBlockM",
            BASELAYER_DDAMAGEH = "Base Layer.DDamageH",
            BASELAYER_DDAMAGEL = "Base Layer.DDamageL",
            BASELAYER_DDAMAGEM = "Base Layer.DDamageM",
            BASELAYER_DMOVE = "Base Layer.DMove",
            BASELAYER_JATKHK = "Base Layer.JAtkHK",
            BASELAYER_JATKHP = "Base Layer.JAtkHP",
            BASELAYER_JATKLK = "Base Layer.JAtkLK",
            BASELAYER_JATKLP = "Base Layer.JAtkLP",
            BASELAYER_JATKMK = "Base Layer.JAtkMK",
            BASELAYER_JATKMP = "Base Layer.JAtkMP",
            BASELAYER_JBLOCKH = "Base Layer.JBlockH",
            BASELAYER_JBLOCKL = "Base Layer.JBlockL",
            BASELAYER_JBLOCKM = "Base Layer.JBlockM",
            BASELAYER_JDAMAGEH = "Base Layer.JDamageH",
            BASELAYER_JDAMAGEL = "Base Layer.JDamageL",
            BASELAYER_JDAMAGEM = "Base Layer.JDamageM",
            BASELAYER_JMOVE_ = "Base Layer.JMove.",
            BASELAYER_JMOVE_JMOVE0 = "Base Layer.JMove.JMove0",
            BASELAYER_JMOVE_JMOVE1 = "Base Layer.JMove.JMove1",
            BASELAYER_JMOVE_JMOVE2 = "Base Layer.JMove.JMove2",
            BASELAYER_JMOVE_JMOVE3 = "Base Layer.JMove.JMove3",
            BASELAYER_JMOVE_JMOVE4 = "Base Layer.JMove.JMove4",
            BASELAYER_OBACKSTEP = "Base Layer.OBackstep",
            BASELAYER_ODOWN = "Base Layer.ODown",
            BASELAYER_ODOWNSDAMAGEH = "Base Layer.ODown_SDamageH",
            BASELAYER_OGIVEUP = "Base Layer.OGiveup",
            BASELAYER_OSTANDUP = "Base Layer.OStandup",
            BASELAYER_SATKHK = "Base Layer.SAtkHK",
            BASELAYER_SATKHP = "Base Layer.SAtkHP",
            BASELAYER_SATKLK = "Base Layer.SAtkLK",
            BASELAYER_SATKLP = "Base Layer.SAtkLP",
            BASELAYER_SATKMK = "Base Layer.SAtkMK",
            BASELAYER_SATKMP = "Base Layer.SAtkMP",
            BASELAYER_SBLOCKH = "Base Layer.SBlockH",
            BASELAYER_SBLOCKL = "Base Layer.SBlockL",
            BASELAYER_SBLOCKM = "Base Layer.SBlockM",
            BASELAYER_SDAMAGEH = "Base Layer.SDamageH",
            BASELAYER_SDAMAGEL = "Base Layer.SDamageL",
            BASELAYER_SDAMAGEM = "Base Layer.SDamageM",
            BASELAYER_SMOVE = "Base Layer.SMove",
            BASELAYER_SWAIT = "Base Layer.SWait"; // semi colon

        public Main_Char3_AbstractAControl()
        {
            Code.Register(StateHash_to_record, new List<AcStateRecordable>()
            {
                new DefaultAcState( BASELAYER_),
                new DefaultAcState( BASELAYER_CATKHK),
                new DefaultAcState( BASELAYER_CATKHP),
                new DefaultAcState( BASELAYER_CATKLK),
                new DefaultAcState( BASELAYER_CATKLP),
                new DefaultAcState( BASELAYER_CATKMK),
                new DefaultAcState( BASELAYER_CATKMP),
                new DefaultAcState( BASELAYER_CBLOCKH),
                new DefaultAcState( BASELAYER_CBLOCKL),
                new DefaultAcState( BASELAYER_CBLOCKM),
                new DefaultAcState( BASELAYER_CDAMAGEH),
                new DefaultAcState( BASELAYER_CDAMAGEL),
                new DefaultAcState( BASELAYER_CDAMAGEM),
                new DefaultAcState( BASELAYER_CMOVE),
                new DefaultAcState( BASELAYER_CWAIT),
                new DefaultAcState( BASELAYER_DATKHK),
                new DefaultAcState( BASELAYER_DATKHP),
                new DefaultAcState( BASELAYER_DATKLK),
                new DefaultAcState( BASELAYER_DATKLP),
                new DefaultAcState( BASELAYER_DATKMK),
                new DefaultAcState( BASELAYER_DATKMP),
                new DefaultAcState( BASELAYER_DBLOCKH),
                new DefaultAcState( BASELAYER_DBLOCKL),
                new DefaultAcState( BASELAYER_DBLOCKM),
                new DefaultAcState( BASELAYER_DDAMAGEH),
                new DefaultAcState( BASELAYER_DDAMAGEL),
                new DefaultAcState( BASELAYER_DDAMAGEM),
                new DefaultAcState( BASELAYER_DMOVE),
                new DefaultAcState( BASELAYER_JATKHK),
                new DefaultAcState( BASELAYER_JATKHP),
                new DefaultAcState( BASELAYER_JATKLK),
                new DefaultAcState( BASELAYER_JATKLP),
                new DefaultAcState( BASELAYER_JATKMK),
                new DefaultAcState( BASELAYER_JATKMP),
                new DefaultAcState( BASELAYER_JBLOCKH),
                new DefaultAcState( BASELAYER_JBLOCKL),
                new DefaultAcState( BASELAYER_JBLOCKM),
                new DefaultAcState( BASELAYER_JDAMAGEH),
                new DefaultAcState( BASELAYER_JDAMAGEL),
                new DefaultAcState( BASELAYER_JDAMAGEM),
                new DefaultAcState( BASELAYER_JMOVE_),
                new DefaultAcState( BASELAYER_JMOVE_JMOVE0),
                new DefaultAcState( BASELAYER_JMOVE_JMOVE1),
                new DefaultAcState( BASELAYER_JMOVE_JMOVE2),
                new DefaultAcState( BASELAYER_JMOVE_JMOVE3),
                new DefaultAcState( BASELAYER_JMOVE_JMOVE4),
                new DefaultAcState( BASELAYER_OBACKSTEP),
                new DefaultAcState( BASELAYER_ODOWN),
                new DefaultAcState( BASELAYER_ODOWNSDAMAGEH),
                new DefaultAcState( BASELAYER_OGIVEUP),
                new DefaultAcState( BASELAYER_OSTANDUP),
                new DefaultAcState( BASELAYER_SATKHK),
                new DefaultAcState( BASELAYER_SATKHP),
                new DefaultAcState( BASELAYER_SATKLK),
                new DefaultAcState( BASELAYER_SATKLP),
                new DefaultAcState( BASELAYER_SATKMK),
                new DefaultAcState( BASELAYER_SATKMP),
                new DefaultAcState( BASELAYER_SBLOCKH),
                new DefaultAcState( BASELAYER_SBLOCKL),
                new DefaultAcState( BASELAYER_SBLOCKM),
                new DefaultAcState( BASELAYER_SDAMAGEH),
                new DefaultAcState( BASELAYER_SDAMAGEL),
                new DefaultAcState( BASELAYER_SDAMAGEM),
                new DefaultAcState( BASELAYER_SMOVE),
                new DefaultAcState( BASELAYER_SWAIT),
            });
        }
    }
}
